import type { SiteContent } from "./types";

// Conteúdo inicial (exemplo). A proprietária substitui tudo pelo painel.
// As imagens em ./img/ são ilustrações provisórias até subir as fotos reais.

export const DEFAULT_CONTENT: SiteContent = {
  general: {
    name: "Cabanas Bambu Cristal",
    tagline: "Refúgio de vidro e bambu",
    heroTitle: "Durma entre as árvores, acorde dentro da paisagem",
    heroSubtitle: "Cabanas de vidro e bambu escondidas na mata, feitas para desacelerar a dois.",
    heroImage: "./img/hero.svg",
    heroVideo: "",
    introTitle: "Arquitetura que some na natureza",
    introText:
      "Cada cabana foi desenhada para emoldurar a floresta: paredes de vidro, estrutura de bambu e nenhum vizinho à vista.\n\nAqui o ritmo é outro. Café da manhã na varanda, banho de ofurô sob as estrelas e o som da mata como trilha sonora.",
    aboutTitle: "Nossa história",
    aboutText:
      "O Bambu Cristal nasceu do desejo de criar um lugar onde o conforto não compete com a natureza, mas conversa com ela. Construímos com bambu tratado, madeira de reflorestamento e muito vidro, para que a paisagem seja sempre a protagonista.",
    aboutImage: "./img/bambuzal.svg",
    whatsapp: "5511999999999",
    instagram: "bambucristal",
    email: "contato@bambucristal.com.br",
    phone: "(11) 99999-9999",
    address: "Estrada da Mata, km 12 · Serra da Mantiqueira · SP",
    mapsEmbed: "Serra da Mantiqueira, SP",
    checkInTime: "14:00",
    checkOutTime: "12:00",
    policies:
      "Check-in a partir das 14h e check-out até 12h.\nNão aceitamos animais de estimação.\nCancelamento gratuito até 15 dias antes da chegada; depois disso o sinal não é devolvido, mas pode ser usado em outra data em até 6 meses.\nProibido fumar dentro das cabanas.",
    paymentInfo: "A reserva é confirmada com 50% de sinal via Pix. O restante é pago no check-in.",
    whatsappIntro: "Olá! Vi o site e gostaria de fazer uma pré-reserva 🌿",
    footerText: "Hospedagem de natureza com conforto. Venha desacelerar.",
    accentColor: "#8a7a4f",
  },
  cabins: [
    {
      id: "cristal",
      slug: "cabana-cristal",
      name: "Cabana Cristal",
      tagline: "Um prisma de vidro suspenso na mata",
      description:
        "Nossa cabana mais icônica: paredes inteiras de vidro, teto alto em formato de A e uma cama posicionada para ver o céu.\n\nTem ofurô aquecido na varanda, lareira ecológica e cozinha compacta equipada.",
      capacity: 2,
      beds: "1 cama king",
      size: "38 m²",
      priceWeekday: 690,
      priceWeekend: 890,
      extraGuestFee: 0,
      baseGuests: 2,
      cleaningFee: 80,
      minNights: 2,
      images: ["./img/cabana-vidro.svg", "./img/cabana-noite.svg", "./img/bambuzal.svg"],
      video: "",
      amenities: ["Ofurô aquecido", "Lareira", "Ar-condicionado", "Wi-Fi", "Cozinha compacta", "Roupa de cama e banho", "Estacionamento"],
      active: true,
    },
    {
      id: "bambu",
      slug: "cabana-bambu",
      name: "Cabana Bambu",
      tagline: "Bambu, luz natural e rede na varanda",
      description:
        "Estrutura aparente de bambu e grandes janelas voltadas para o bambuzal. Ideal para quem quer silêncio e uma varanda gostosa para ler.\n\nAcomoda até 3 pessoas com um sofá-cama.",
      capacity: 3,
      beds: "1 cama queen + 1 sofá-cama",
      size: "42 m²",
      priceWeekday: 520,
      priceWeekend: 690,
      extraGuestFee: 90,
      baseGuests: 2,
      cleaningFee: 80,
      minNights: 2,
      images: ["./img/cabana-bambu.svg", "./img/bambuzal.svg"],
      video: "",
      amenities: ["Rede na varanda", "Chuveiro a gás", "Wi-Fi", "Frigobar", "Cafeteira", "Roupa de cama e banho"],
      active: true,
    },
    {
      id: "lago",
      slug: "cabana-lago",
      name: "Cabana do Lago",
      tagline: "Deck sobre a água para o pôr do sol",
      description:
        "Uma cabana de vidro à beira do lago, com deck privativo e caiaque à disposição.\n\nPerfeita para famílias pequenas: quarto de casal e mezanino com duas camas de solteiro.",
      capacity: 4,
      beds: "1 cama queen + 2 de solteiro",
      size: "55 m²",
      priceWeekday: 780,
      priceWeekend: 980,
      extraGuestFee: 100,
      baseGuests: 2,
      cleaningFee: 120,
      minNights: 2,
      images: ["./img/cabana-lago.svg", "./img/cabana-vidro.svg"],
      video: "",
      amenities: ["Deck privativo", "Caiaque", "Churrasqueira", "Wi-Fi", "Cozinha completa", "Ar-condicionado"],
      active: true,
    },
  ],
  extras: [
    { id: "cafe", name: "Café da manhã na cesta", description: "Entregue na porta da cabana todas as manhãs.", price: 70, unit: "guest", active: true },
    { id: "romantica", name: "Decoração romântica", description: "Pétalas, velas, espumante e chocolates.", price: 250, unit: "stay", active: true },
    { id: "fondue", name: "Noite do fondue", description: "Fondue de queijo e chocolate para dois.", price: 180, unit: "stay", active: true },
  ],
  experiences: [
    { id: "e1", title: "Ofurô sob as estrelas", text: "Água quente, céu limpo e nenhuma luz da cidade por perto.", image: "./img/cabana-noite.svg" },
    { id: "e2", title: "Trilha do bambuzal", text: "Um caminho de 2 km entre bambus gigantes até a cachoeira.", image: "./img/bambuzal.svg" },
    { id: "e3", title: "Pôr do sol no lago", text: "Caiaque, deck e um vinho para encerrar o dia.", image: "./img/cabana-lago.svg" },
  ],
  faqs: [
    { id: "f1", question: "Como faço para reservar?", answer: "Escolha a cabana, selecione as datas no calendário e envie a pré-reserva pelo WhatsApp. Respondemos confirmando a disponibilidade e os dados para o sinal." },
    { id: "f2", question: "Crianças são bem-vindas?", answer: "Sim, na Cabana do Lago e na Cabana Bambu. A Cabana Cristal é exclusiva para casais." },
    { id: "f3", question: "Tem sinal de celular e Wi-Fi?", answer: "Temos Wi-Fi em todas as cabanas. O sinal de celular varia conforme a operadora." },
    { id: "f4", question: "Precisa de carro 4x4?", answer: "Não. O acesso tem 3 km de estrada de terra em bom estado, tranquilo para qualquer carro." },
  ],
  testimonials: [
    { id: "t1", name: "Mariana e Lucas", text: "Acordar vendo a mata pela parede de vidro foi inesquecível. Voltaremos!" },
    { id: "t2", name: "Juliana", text: "Atendimento impecável e a cabana é ainda mais linda pessoalmente." },
  ],
  specialPrices: [],
  gallery: ["./img/cabana-vidro.svg", "./img/cabana-bambu.svg", "./img/cabana-lago.svg", "./img/cabana-noite.svg", "./img/bambuzal.svg", "./img/hero.svg"],
};
